export const GET_BOOKS = 'GET_BOOKS';
export const ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART';
export const REMOVE_BOOK_FROM_CART = 'REMOVE_BOOK_FROM_CART';
export const ON_EMPTY_CART = 'ON_EMPTY_CART';
export const UPDATE_CART_QTY_PLUS = 'UPDATE_CART_QTY_PLUS';
export const UPDATE_CART_QTY_MOINS = 'UPDATE_CART_QTY_MOINS';
export const COMMERCIAL_OFFRES = 'COMMERCIAL_OFFRES';
